varsion: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: ls
      - run: sudo composer self-update --1
      - run: 
          working_directory: laravel
          command: composer install -n --prefer-dist
      - run:
          working_directory: laravel
          command: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vemdor/bin/phpunit
